### ISSUE TITLE
Motion like switching

### ISSUE THREAD

**Issue by Willem-J-an** [yorickpeterse/nvim-window#1]
Hi @yorickpeterse,

I like the plugin, but I feel like it would be even better to have a motion like switching experience.

Now I press <leader>w, wait for the numbers to appear, then press the number.

The experience I would like is:
press <leader>w+number -> it instantly jumps. When you already know the window number, it helps a lot.
press <leader>w -> original behavior where it starts showing numbers. This is still helpful when you don't know the window number.

What do you think :smile:

**Comment by yorickpeterse** [comment]
Smarter switching like this, or automatically switching to the previous window (or anything like that) is out of the scope :smiley: 

If you're constantly switching between the same two windows, the easiest way is to just use <kbd>Control</kbd> + <kbd>W</kbd> + <kbd>p</kbd> to switch between the current and previous window.
