### ISSUE TITLE
How to use was neo-tree window picker

### ISSUE THREAD

**Issue by mikaoelitiana** [yorickpeterse/nvim-window#9]
Is there an easy way to integrate this plugin as [neo-tree's](https://github.com/nvim-neo-tree/neo-tree.nvim) window picker? Neo-tree has the `w` keymap to open a file in a picked window and I would like to use `nvim-window` instead of `s1n7ax/nvim-window-picker`

**Comment by yorickpeterse** [comment]
I don't use nor am I familiar with neo-tree. nvim-window only concerns itself with switching between Neovim windows and nothing more. If you want to somehow combine the two, you'll probably need to create your own plugin.
